Dockerfile
-------------------

A Dockerfile is a text document that contains all the commands a user could call on the command line to assemble an image.
Using docker build users can create an automated build that executes several command-line instructions in succession.

Usage
    The docker build command builds an image from a Dockerfile and a context.
